SRCS += 
SRCS += Sources/actions/ph_died.c
SRCS += Sources/actions/ph_eat.c
SRCS += Sources/actions/ph_fork.c
SRCS += Sources/actions/ph_sleep.c
SRCS += Sources/actions/ph_think.c
SRCS += Sources/init/ph_init.c
SRCS += Sources/main.c
SRCS += Sources/parsing/ph_parsing.c
SRCS += Sources/utils/ph_atoi.c
SRCS += Sources/utils/ph_display.c
SRCS += Sources/utils/ph_time.c
